### ISSUE TITLE
  ERROR! bed file does not exsit

### ISSUE THREAD

**Issue by nm15336** [saigegit/SAIGE#101]
Hi, I am running step 1 of saige using plink genetic files. However I am getting the error:
```
Error in fitNULLGLMM(plinkFile = opt$plinkFile, bedFile = opt$bedFile,  :
  Error in fitNULLGLMM(plinkFile = opt$plinkFile, bedFile = opt$bedFile,  :
  ERROR! bed file does not exsit

```
The data do exist, is in the right dir, and I have tried renaming the files, changing their location, adding and removing "", but get the same error. 

Is this because I am calling it through a singularity module? Is there a reason it would not recognise the files?

```
singularity exec ${saigeDir} step1_fitNULLGLMM.R \
```

Or do you know what else could be causing this? Full .out file attached.
Thanks!
[saige-error-git.txt](https://github.com/saigegit/SAIGE/files/11866263/saige-error-git.txt)

**Comment by kscott-1** [comment]
In general when working with containers, you will need to mount your data into the container

`apptainer exec --bind /path/to/plinkfile:/mnt .......`

Then your plink files will all be located in the /mnt directory within your container

I suggest reading through the [apptainer docs](https://apptainer.org/docs/user/main/bind_paths_and_mounts.html)

**Comment by nm15336** [comment]
Thank you!
