### ISSUE TITLE
fitNULLGLMM: glmmkin.ai_PCG_Rcpp_Binary -> Get_Coef -> getCoefficients - spsolve(): memory allocation failure

### ISSUE THREAD

**Issue by JonChan0** [saigegit/SAIGE#109]
Hi,

I am using SAIGE R package on a cluster node (>100 GB of RAM free) to try run step1: fitting the null GLMM using the following R script - [saige_step1_submission.txt](https://github.com/saigegit/SAIGE/files/12430089/saige_step1_submission.txt)

However, this results in the following issue:

``` 
[1] "Genotype reading is done"
inital tau is  1 0.1
use sparse kinship to fit the model
Not enough memory to perform factorization.

warning: spsolve(): memory allocation failure
Error in getCoefficients(Y, X, W, tau, maxiter = maxiterPCG, tol = tolPCG) :
  spsolve(): solution not found
Calls: fitNULLGLMM ... glmmkin.ai_PCG_Rcpp_Binary -> Get_Coef -> getCoefficients
Timing stopped at: 130.1 1.001 131.5
Execution halted
```

This has been replicated across both UK Biobank's Research Access Platform using the Docker image: wzhou88/saige:1.2.0 as well as on UK Biobank's Research Access Platform's RStudio Workbench following install from source code, as well as on the aforementioned environment of local install (Conda) on another cluster node environment.

Full log attached below
[rescomp_saige_gene_errorlog.txt](https://github.com/saigegit/SAIGE/files/12430078/rescomp_saige_gene_errorlog.txt)

**Comment by JonChan0** [comment]
Issue resolved with using different input files into step1.

**Comment by JonChan0** [comment]
Hii @embertucci, I changed all input files:
- Sparse GRM with their Rscript with a different subset of individuals.
- Random markers used for variance ratio estimation using hard-called genotypes from those different subset.
- Phenotype file according to those different subset.

**Comment by embertucci** [comment]
@JonChan0 thank you for your quick response - much appreciated!
