### ISSUE TITLE
MACVec_forVarianceRatio

### ISSUE THREAD

**Issue by LaporteF** [saigegit/SAIGE#11]
Hi,

In this version, a maxMAC is automatically set for the Variance Ratio Estimation even if you set isCateVarianceRatio=FALSE :

https://github.com/saigegit/SAIGE/blob/b84a44b7ed85e84d3c8fd481c9fa7e20169b1b1d/R/SAIGE_fitGLMM_fast.R#L1100

In the previous version only a minMAC was set. Is it a mistake or is there a reason for this modification?

Regards.

**Comment by saigegit** [comment]
Hi @LaporteF, 

In this new version, we assign the markers used for GRM and for variance ratio estimation while reading in the PLINK file. This change was made to make sure the markers are only used for one of the purposes. Thanks for the reminding. I double checked the setting and further revised the code in v1.0.3

**Comment by LaporteF** [comment]
Hi @saigegit,

Thank you for your hard work and your answers for this software. 
The issue here is with a dataset of 6000 individuals and a MAF for the GRM set at 0.05, the maxMAC_varRatio is set near 125. I have no variant with a MAC lower than 125 and so the step1 crashed and displayed this message:

"Error in scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait(obj.glmm.null = modglmm,  :                                                                                                                                                           No markers were found for variance ratio estimation. Please make sure there are at least 200 markers in each MAC category"

And in the output I found:

"length(MACvector):  92779                                                                                                                                                                                                                    length(MACvector_forVarRatio):  0 "

That is why I believe the maxMAC_varRatio must not be set or at least set as:

"maxMAC_varRatio = Number_Of_Individuals - mac_inter"

Regards

**Comment by LaporteF** [comment]
I close this issue. The version 1.0.3 has solved it.

Thanks
