### ISSUE TITLE
Step 2 - annotations not recognized upon reading new chunk of regions

### ISSUE THREAD

**Issue by tammy-dg** [saigegit/SAIGE#13]
Hello all,

I have found that when I specify multiple annotation sets for Step 2 - for example: `--annotation_in_groupTest=PTV_f5_f01,PTV_f5`, when the end of the first chunk of regions is encountered, the following error is encountered:
```
Error in SAIGE.getRegionList_new(marker_group_line, nline_per_gene, annolist,  : 
  At least one annotation is required
Calls: SPAGMMATtest -> SAIGE.Region -> SAIGE.getRegionList_new
Execution halted
```

However, when I change `--groups_per_chunk` to some number that is larger than the number of regions in my group file (so that there are not multiple chunks read in), then this error is never encountered.

Please let me know if you need any more information. Thank you!

**Comment by saigegit** [comment]
Hi @tammy-dg, 

Thanks so much for reporting this issue.  It should have been fixed in the v1.0.3

Thanks,
Wei
