### ISSUE TITLE
SAIGE build failure within conda: error: expected ')' before 'PRId64'

### ISSUE THREAD

**Issue by pettyalex** [saigegit/SAIGE#17]
I'm getting a compilation failure when building VCF.cpp inside of conda that can be worked around by reordering imports. I will make a PR that does this.

The root cause is that Rcpp and headers that include it includes `<inttypes.h>`, which varies in behavior based on what macros are set. Basically, in order for the macros defined in `<cinttypes>` to work portably across most C environments, `<cinttypes>` must be included before `<inttypes.h>`, or a specific macro (`__STDC_FORMAT_MACROS`) must be set. There's more detail here, when I thought that this issue was related to savvy rather than SAIGE: https://github.com/statgen/savvy/issues/23

I chased this around for a while, and the most straightforward solution for SAIGE is to re-order includes such that Rcpp and Rcpp* headers comes after other headers. This solution was recommended by the Rcpp author as well: https://github.com/RcppCore/Rcpp/issues/1210. I don't know if it's wise to make this change everywhere that Rcpp headers are included, or only in the one place breaking the build right now.

The build failure looks like this:
```
../thirdParty/cget/include/savvy/typed_value.hpp: In member function 'void savvy::typed_value::serialize_vcf(std::size_t, char*&, char) const':
../thirdParty/cget/include/savvy/typed_value.hpp:2955:40: error: expected ')' before 'PRId64'
 2955 |       else out += std::sprintf(out, "%" PRId64, v);
      |                               ~        ^~~~~~~
      |                                        )
```

**Comment by lganel** [comment]
I had this error as well, but your solution didn't work for me.

When I tried your PR (using `gh pr checkout 18`), I got the below error:
`In file included from VCF.cpp:16:0:
/gstore/home/ganell/miniconda3/envs/RSAIGE/lib/R/library/RcppArmadillo/include/RcppArmadillo.h:25:6: error: #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArmadillo.h'."
     #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArmadillo.h'."
      ^~~~~`

I tried removing the `#include Rcpp.h`, but that recapitulated the original `expected ')' before 'PRId64'` error...

**Comment by pettyalex** [comment]
@lganel There's a couple of other solutions that should work instead. I still haven't decided which one would be best long term.

You can add `-D__stdc_format_macros` to `PKG_CPPFLAGS` in `src/Makevars`, right after `-DARMA_64BIT_WORD=1`.
You could #include <cinttypes> at the top of VCF.cpp.

Also, what OS and g++ are you on? You will need a somewhat recent g++ in general for this to work.

**Comment by pettyalex** [comment]
OK, I got the include ordering working, but it touched a lot of files and would take manual maintenance to prevent future breakage. I'm going to make another PR that adds `-D__STDC_FORMAT_MACROS` to fix this.

Were you running this inside of conda?

**Comment by pettyalex** [comment]
@lganel try this: https://github.com/saigegit/SAIGE/pull/19

**Comment by lganel** [comment]
Thanks so much @pettyalex! I'm on CentOS 7.7.1908 and g++ 4.8.5.
Yes, I am trying to build SAIGE using conda - I'm following the instructions [here](https://saigegit.github.io//SAIGE-doc/docs/Installation_conda.html) but getting errors at the `R CMD INSTALL` line.
I tried your PR #19 and it seems to have worked! The `R CMD INSTALL` command completed successfully and I'm able to load SAIGE in R.
Thanks so much, kind stranger!!

**Comment by kousikbioinfo** [comment]
Hi folks, 
I am having the similar problem that @lganel had earlier. I am installing SAIGE through conda by following [this](https://saigegit.github.io//SAIGE-doc/docs/Installation_conda.html), but getting error `R CMD INSTALL`. 
See the error below - 
```
(RSAIGE) [Kousik@AZ-scp - Software] $ R CMD INSTALL SAIGE
* installing to library ‘/projects/cgr/users/klds407/.conda_env/RSAIGE/lib/R/library’
* installing *source* package ‘SAIGE’ ...
** using staged installation
Ignore package xz
Downloading https://github.com/statgen/savvy/archive/v2.1.0.tar.gz
Download failed with error 501 for: //github.com/statgen/savvy/archive/v2.1.0.tar.gz
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/projects/cgr/users/klds407/.conda_env/RSAIGE/lib/R/library/SAIGE’
(RSAIGE) [Kousik@AZ-scp - Software] $ cd /projects/cgr/users/klds407/.conda_env/RSAIGE
```

If I understood correctly, adding `-D__STDC_FORMAT_MACROS` to `PKG_CPPFLAGS` in `src/Makevars` - if not could you correct me please @lganel @pettyalex 

But I am unable to find the file I need to modify. Could you please help me in this regard. Thanks in advance.
