### ISSUE TITLE
Sample File

### ISSUE THREAD

**Issue by eugenegardner** [saigegit/SAIGE#2]
Hello,

The .sample file provided to SAIGE (via --sampleFile) does not appear to follow bgen defaults. When I provide either the qctool default sample:

```
ID missing sex
0 0 D
123456 0 NA
```

or plink2 default sample:

```
ID_1 ID_2 missing sex
0 0 0 D
123456 0 NA
```

SAIGE throws an error.

However, if I remove the header entirely:

```
123456 0 NA
```

SAIGE now runs properly.

Thanks!

**Comment by weizhou0** [comment]
Yes, please see the description for the sample file in the doc
#2 
https://saigegit.github.io//SAIGE-doc/docs/single_step2.html#input-files

Thanks!

**Comment by eugenegardner** [comment]
Yes, I saw that, but I guess my question was why you don't allow use of the default bgen .sample file? This requires additional processing on the part of the user.

**Comment by weizhou0** [comment]
Hi @eugenegardner, 

Thanks for the suggestion! v1.0.2 now supports the default bgen sample file.
