### ISSUE TITLE
Conditional analysis - step 2

### ISSUE THREAD

**Issue by damichalek** [saigegit/SAIGE#21]
Hi,

I have used SAIGE (v1.0.1) for conditional analysis. When I try `--condition` with only one SNP, then conditional analysis works, but when I add second SNP I got an error (I separate SNPs with coma).

```
Error in assign_conditionMarkers_factors(genoType, condition_genoIndex_prev_a,  : 
  inv(): matrix is singular
Calls: SPAGMMATtest -> assign_conditionMarkers_factors
Execution halted
```

If you need more information, please let me know. Thank you!

**Comment by saigegit** [comment]
Hi @damichalek, 

This error is because the conditional markers are not specified in the order of chromosome and position. For example, it should be --condition=1:4:A:C,1:9:A:C instead of --condition=1:9:A:C,1:4:A:C. 

Thanks,
Wei

**Comment by damichalek** [comment]
Hi Wei,

I forgot to mention that the issue was resolved, since we have talked about it few days ago. Thank you for your help!
