### ISSUE TITLE
Single variant association test results from region based test

### ISSUE THREAD

**Issue by tammy-dg** [saigegit/SAIGE#22]
Hi all,

I have a couple of questions about the single variant association test output when running SAIGE-GENE+ in region-based testing mode.

I have attached a subset outputs for both the region- and single variant- test outputs:
[region_output.txt](https://github.com/saigegit/SAIGE/files/8516752/region_output.txt)
[single_var_output.txt](https://github.com/saigegit/SAIGE/files/8516753/single_var_output.txt)

My first question is whether there are additional, unintended columns for conditional analysis that have been included in the output (I have not passed anything into `--condition` when running Step 2). I think this is the case because the final two columns in the single-var output (`N_case` and `N_ctrl`) are empty, but it really just looks to be a mis-alignment of the number of columns in the header and in the output rows. In the attached file, it looks `Is.SPA` (since this isn't documented in the [docs](https://saigegit.github.io//SAIGE-doc/docs/single_step2.html#output-file)) and `p.value.NA_c` (since this is documented to be a conditional analysis specific column) should be removed.

~My second question depends on whether the first point above is true. If that is true, then in the first row the variant `chr1_33306784_G_GTACCCC` should be `AF_case = 0` and `AF_ctrl = 0.00011188`). However, I would expect `AF_ctrl` to equal `AF_Allele2` (since there are no occurrences of that marker in the cases), but that doesn't seem to be the case. Is my assumption correct?~ Edit: Silly error on my end when thinking about this! Nevermind on this point.

Lastly, I wanted to ask for clarification about the 'UR' rows in the output. My assumption is that the UR stands for "ultra-rare" and these are the results from collapsing all ultra-rare variants for each group and performing the test for association. (Sorry I couldn't find any mention about this in your docs).

Thank you again for your time and development on your great tool!

Tammy

**Comment by saigegit** [comment]
Hi @tammy-dg, 

The extra columns in the header line have been removed in v1.0.5. 
You are correct about the UR rows, these are for the collapsed ultra-rare variants. Thanks for the note. I will add the information to the documentation. 

Thanks,
Wei

**Comment by tammy-dg** [comment]
Thank you for your time and response, Wei and sorry for this late response. I will close this now as you've answered my questions!
