### ISSUE TITLE
Issue with chromosomes 1 through 9

### ISSUE THREAD

**Issue by catrionakbarnes** [saigegit/SAIGE#26]
I'm running the following command using the docker image `docker.io/wzhou88/saige:1.0.1`:

(example shown here for chromosome 9)

```
Rscript step2_SPAtests.R \
  --bgenFile=mybgen_chr9.bgen \
  --bgenFileIndex=mybgi_chr9.bgen.bgi \
  --sampleFile=mysamplefile.txt \
  --AlleleOrder=ref-first \
  --SAIGEOutputFile=myoutput_chr9.txt \
  --chrom=9 \
  --idstoIncludeFile=my_snps_chr9.txt \
  --minMAF=0.01 \
  --minMAC=20 \
  --GMMATmodelFile=saige_step1.rda \
  --varianceRatioFile=saige_step1.varianceRatio.txt  \
  --is_Firth_beta=TRUE \
  --pCutoffforFirth=0.1
```

I have run this for chromosomes 1 to 22 on UK Biobank data files. Chromosomes 10 through 22 run perfectly, however I'm getting an error with chromosomes 1 to 9:

```
Setting position of samples in Bgen files....
Error in SAIGE.Marker(traitType, genoType, objGeno$markerInfo$genoIndex_prev,  :
  No markers on chrom 9 are found
Calls: SPAGMMATtest -> SAIGE.Marker
Execution halted
```

I have checked all files - they are all in the correct locations, with the correct names, and the SNPs listed for inclusion for `idstoIncludeFile` are present within the data. The fact that it is specificially the single digit chromosomes that are failing suggests that there is potentially some naming error somewhere (where the code is expecting a two digit number, eg. 09 as opposed to 9).  Do you have any idea what might be causing this error and how it can be corrected?

**Comment by mohasal12** [comment]
I am running the following command

`/usr/bin/time -v Rscript step2_SPAtests.R	\
  --vcfFile=/mnt/archive/mohasal/vcf/CHR22_PID112437.vcf.gz \
  --vcfFileIndex=/mnt/archive/mohasal/vcf/CHR22_PID112437.vcf.gz.csi \
  --vcfField=GT \
  --chrom=1 \
  --minMAF=0 \
  --minMAC=3 \
  --GMMATmodelFile=/mnt/scratch/mohasal/huntsaigeout/CD.rda \
  --varianceRatioFile=/mnt/scratch/mohasal/huntsaigeout/CD.varianceRatio.txt \
  --SAIGEOutputFile=/mnt/scratch/mohasal/huntsaigeout/CD.SAIGE.vcf.genotype.txt \
  --LOCO=FALSE
  `

And the output shown is 
`Error in SAIGE.Marker(traitType, genoType, objGeno$markerInfo$genoIndex_prev,  :
  No markers are left in VCF
Calls: SPAGMMATtest -> SAIGE.Marker
Execution halted
`
I tried it on other chromosomes as well only to get the same result. What might I be doing wrong here?

**Comment by Eloise-Zhou** [comment]
> > [@mohasal12](https://github.com/mohasal12) hey, have you solved this problem? I just encounter the same issue and I'm confused about it. Thanks!
> > Error:
> > ```
> > Error in SAIGE.Marker(traitType, genoType, objGeno$markerInfo$genoIndex_prev,  :  
> > No markers are left in VCF
> > Calls: SPAGMMATtest -> SAIGE.Marker
> > Execution halted
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Command:
> > ```
> > Rscript ${conda_path}/step2_SPAtests.R        \  
> >         --vcfFile=${genotype_path}/${i}_vt_rare.vcf.gz    \
> >         --vcfFileIndex=${genotype_path}/${i}_vt_rare.vcf.gz.csi     \
> >         --vcfField=GT   \
> >         --SAIGEOutputFile=./output/${i}_quantitative_30566_results.txt    \
> >         --chrom=1       \
> >         --minMAF=0 \
> >         --minMAC=20 \
> >         --GMMATmodelFile=${nullmodel_path}/quantitative_sparseGRM_vr_clean.rda \
> >         --varianceRatioFile=${nullmodel_path}/quantitative_sparseGRM_vr_clean.varianceRatio.txt  \
> >         --LOCO=FALSE \
> >         --sparseGRMFile=${sparseGRM_path}/new_sparseGRM.mtx   \
> >         --sparseGRMSampleIDFile=${sparseGRM_path}/new_sparseGRM.mtx.sampleIDs.txt \
> >         --is_fastTest=TRUE &> ${i}.out
> > ```
> 
> I am unable to recall, but looking at the code now, in my case, it seems that I was passing chr 22 vcf file and filtering for chrom=1, which left me with no variants.
> 
> In your code, the problem might be similar that the filtering condition (perhaps MAC is set too high) set leads to the variants being excluded, perhaps test by relaxing the MAC.


Thanks for your advise!  However, I double check the input VCF file and the corresponding chromosome number again, and I'm sure they are correct. Meanwhile, I have set `--minMAC=1`, but I still encounter the same error. It makes me so confused.
