### ISSUE TITLE
Drop missing dosages

### ISSUE THREAD

**Issue by kousathanas** [saigegit/SAIGE#28]
Hi,

I cannot see the old option --IsDropMissingDosages

there is a new option "--impute_method", but it doesnt have the possibility to drop missing dosages. Is there another way to do this, or is this something to be implemented in the future?

**Comment by saigegit** [comment]
Hi, 
Yes the option to drop missing dosages has not been implemented in the current version.  It is to be implemented in the future. 

Thanks,
Wei
