### ISSUE TITLE
groupFile issue

### ISSUE THREAD

**Issue by yonas-yuh** [saigegit/SAIGE#29]
Hi, 

While checking groupFile on set-based test, checkGroupFile seems to having an issue. 

The function `marker_group_line_list = strsplit(marker_group_line, split=c(" +", "\t"))[[1]]` can split multiple spaces, but it couldn't split tab properly.

As strsplit supports the regex, wouldn't it be better split="[\ \t]+" ?

Regards

**Comment by weizhouUMICH** [comment]
Hi, 
Great catch! We are changing to  split="[\ \t]+" in the new version 1.0.6. Will let you know when it has been well tested. 

Thanks,
Wei

**Comment by weizhouUMICH** [comment]
Hi @yonas-yuh, 

The change has been done in the version 1.0.6. Thanks!

Wei
