### ISSUE TITLE
SAIGE from source code. No MetaSKAT.

### ISSUE THREAD

**Issue by FrederikFilip** [saigegit/SAIGE#3]
More a FYI than an actual issue.

When trying to install SAIGE from [source code](https://saigegit.github.io//SAIGE-doc/docs/Installation_sourcecode.html), I first ran the installation of dependencies

` Rscript ./SAIGE/extdata/install_packages.R`

but the package 'MetaSKAT' was not installed, so I had to download it and install it like this:

```
wget https://cran.r-project.org/src/contrib/Archive/MetaSKAT/MetaSKAT_0.81.tar.gz
tar -xvf MetaSKAT_0.81.tar.gz
rm MetaSKAT_0.81.tar.gz
R CMD INSTALL MetaSKAT
```
After this everything compiled, and I was able to run the provided examples.

**Comment by saigegit** [comment]
devtools::install_github("leeshawn/MetaSKAT")

is now added to the ./SAIGE/extdata/install_packages.R

**Comment by vivekruhela** [comment]
Hi,

I am still not able to install MetaSKAT using the following command:

devtools::install_github("leeshawn/MetaSKAT")

Also, I am facing the same isue with sparsesvd package. Could you please suggest how tofix it? Thanks
