### ISSUE TITLE
issue in step0 and the step2

### ISSUE THREAD

**Issue by xingejun** [saigegit/SAIGE#34]
Hi, 
I have try to run SAIGE and SAIGE-GENE for two weeks refer to your code in “https://saigegit.github.io//SAIGE-doc/docs/UK_Biobank_WES_analysis.html” and  now I can run it.

However,there are two situations unclearly.

Firstly, there is a problom which I realised today. It is about the below command. I think it is strange why "2*$6-$5" is used here. I have searched the plink2 document as the picture that the column $6 refers to the number of allele observations. And my opinion is MAC=$5 or MAC=$6-$5;
![image](https://user-images.githubusercontent.com/92867192/170850322-512258ed-abee-4dfd-8904-e91fc4aed766.png)

```
#2 randomly extract IDs for markers falling in the two MAC categories
cat <(tail -n +2 ${OUTPUT_prefix_counts}.acount | awk '((2*$6-$5) < 20 && (2*$6-$5) >= 10) || ($5 < 20 && $5 >= 10) {print $2}' | shuf -n 1000) \
<(tail -n +2 ${OUTPUT_prefix_counts}.acount | awk ' $5 >= 20 && (2*$6-$5)>= 20 {print $2}' | shuf -n 1000) > ${OUTPUT_prefix_counts}.markerid.list
```
My second problem is that I do not sure if I can put X chromsome in STEP1(both SAIGE and SAIGE-GENE; without GRM estimated just to construct  the null model).

I will very appericiate it if you could reply!

**Comment by saigegit** [comment]
Hi @xingejun, 

For the first question, good catch! I think you are right, it should be $5 or $6-$5.  Thanks for letting us know. 
For the second question, only autosomal markers are used for variance ratio estimation, so you don't need to include X chromosome in Step 1. 

Thanks,
Wei

**Comment by xingejun** [comment]
Hi @weizhouUMICH 

Got it, thank you very much for your reply. 

Thanks again,
Xin
