### ISSUE TITLE
Error in SPAGMMATtest

### ISSUE THREAD

**Issue by xingejun** [saigegit/SAIGE#35]
Hi, Wei,

I was trying with your new version of SAIGE 1.1.1. But there is a strange issue with SPAGMMATtest. It may be useful that a certain chromosome(which was the first chromosome in both bim file and group file) can be done with the new version while others can not. The error message was as follows.

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/92867192/173550191-02331adc-2d74-4373-9afb-0de0ec387d7a.png">

Looking forward to your reply.

Thanks,
Xinxin

**Comment by xingejun** [comment]
Hi Wei,

The issue has been done with group file specified. However, there was another issue I can't handle with it.
Every time I run with X chromosome in STEP 2 (GRM and variance ratio was estimated with chromosome 1-22 ), it came up. The error message was as follows:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/92867192/174233667-0c6b7257-c3f4-43f7-9461-4d9d160df621.png">

My command is as follows, is anything wrong with it? And what should i do to avoid it?

Rscript  ./SAIGE/extdata/step2_SPAtests.R        
--bedFile=./3Pheno_corhort_chrX.bed       
--bimFile=./3Pheno_corhort_chrX.bim       
--famFile=./3Pheno_corhort_chrX.fam       
--SAIGEOutputFile=./va_1_20/va_1_20_chr23.txt 
--AlleleOrder=alt-first 
--chrom=X  
--minMAF=0 
--minMAC=0.5 
--GMMATmodelFile=./null-model-new/step1_va_1_20_saige_gene.rda 
--varianceRatioFile=./null-model-new/step1_va_1_20_saige_gene.varianceRatio.txt   
--sparseGRMFile=./step1_relatednessCutoff_0.125_5000_randomMarkersUsed.sparseGRM.mtx  ------
--sparseGRMSampleIDFile=./step1_relatednessCutoff_0.125_5000_randomMarkersUsed.sparseGRM.mtx.sampleIDs.txt 
--groupFile=./group_file_x.txt    
--annotation_in_groupTest=HIGH,HIGH:MODERATE        
--maxMAF_in_groupTest=0.0001,0.001,0.01    
--LOCO=FALSE 
--is_fastTest=TRUE

>

 I will be very grateful if you could reply.

Thank you very much
xinxin

**Comment by saigegit** [comment]
Hi Xinxin, 

Sorry for my late reply. If seems the sample IDs in the fam file ./3Pheno_corhort_chrX.fam are not matching sample IDs in the step 1. Can you please check? 

Thanks,
Wei

**Comment by xingejun** [comment]
Hi Wei,

Thank you very much and your advice helps me a lot.

Thanks,
Xinxin

**Comment by xingejun** [comment]
Hi Wei,

The same error occured when I used the matching .fam file and samples IDs in the step1,
