### ISSUE TITLE
plinkfile and bgen file with dosage

### ISSUE THREAD

**Issue by xingejun** [saigegit/SAIGE#36]
Hi Wei,

I am confused with if SAIGE and SAIGE-GENE support the dosage(DS) imputed not GT for input of plinkfile or bgen file and how to set the parameter to do it. 

Looking forward to your reply!
Xinxin

**Comment by saigegit** [comment]
Hi Xinxin, 

SAIGE and SAIGE-GENE support the bgen (contains dosages) and plink binary file (bim, bed, fam contains genotypes). For VCF, both are DS and GT are supported with --vcfField=GT or DS specified. 

Thanks,
Wei

**Comment by xingejun** [comment]
Hi Wei,

Thanks for your reply!

Xinxin
