### ISSUE TITLE
the --vcfFileIndex option seems to be ignored

### ISSUE THREAD

**Issue by pettyalex** [saigegit/SAIGE#38]
I noticed that the `--vcfFileIndex` option does not actually seem to be used at any point during the analysis. Instead, I see that the VCF file path is being passed into savvy without any reference to the index. When using VCFs or BCFs, it seems hard coded to require a .csi index that's right next to the file in the same directory.

Can the documentation be updated to indicate this? Also, I'd be willing to help remove everything about `--vcfFileIndex` from the code, because right now it's being passed all the way through R into the `VcfClass::setVcfObj` method where it is completely unused. I also see it's in SAIGE-GENE unused in `setvcfDosageMatrix`. It would simplify the code if all references to `--vcfFileIndex` were removed, given that it isn't used.

**Comment by saigegit** [comment]
Hi Alex, 

Thanks so much for catching this and offering help to remove codes with vcfFileIndex! Please feel free to do so. 

Thanks,
Wei
