### ISSUE TITLE
method of conditional association analysis in SAIGE

### ISSUE THREAD

**Issue by xingejun** [saigegit/SAIGE#41]
Hi Wei,

I would like to know about the method of conditional analysis supplemented in SAIGE. I have searched for the paper pulished for SAIGE but no detailed information was found. All I know is that the conditional analysis was based on summary GWAS analysis. Could you help me know more details about the conditional analysis  in SAIGE?

Thank you very much and looking forward to your reply.

Best,
Xinxin

**Comment by saigegit** [comment]
HI Xinxin, 

The details of the approach can be found in the supplementary note of the SAIGE-GENE paper
[https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-020-0621-6/MediaObjects/41588_2020_621_MOESM1_ESM.pdf](https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-020-0621-6/MediaObjects/41588_2020_621_MOESM1_ESM.pdf)

Thanks,
Wei
