### ISSUE TITLE
options to analyze savfile and vcffile by region? 

### ISSUE THREAD

**Issue by brettva** [saigegit/SAIGE#45]
Hello,

Just wondering if there is an option to analyze vcf and sav files by region. With older version .45 of SAIGE  I used to be able to supply:

SPAGMMATtest(vcfFile = vcfFile,
			vcfFileIndex = vcfFileIndex,
			chrom = chrom,
			start = start,
			end = end)

I see the documentation here specifies https://saigegit.github.io//SAIGE-doc/docs/single_step2.html:

```
To query and test a subset of markers
both variant IDs (chr:pos:ref:alt) and range of chromosome positions (chr start end) can be specified for BGEN input (–idstoIncludeFile, –rangestoIncludeFile)
```

Is this option available for vcf and sav? Is there currently any way to test a subset of markers for sav and vcf?

Thanks!

**Comment by weizhou0** [comment]
Hi @brettva, 

Please check the new version 1.1.6. We have added the options for sav and vcf. 
Both variant IDs (chr:pos:ref:alt) and range of chromosome position (chr start end) can be used (`--idstoIncludeFile=./input/includeID.list_1`, `--rangestoIncludeFile=./input/includerange_oneline.txt`)

Note that the two options can't be used at the same time for sav and vcf input and when query with range, only one range can be used for sav and vcf inout. You may check the file `./input/includerange_oneline.txt`. It only contains one line. 

Thanks!
Wei
