### ISSUE TITLE
Firth SE

### ISSUE THREAD

**Issue by bgorm** [saigegit/SAIGE#46]
Hi Wei,

When Firth mode is enabled, the beta estimates appear to be more accurate for some SNPs, but z (beta/se) no longer corresponds to the p-value given in the p.value column. It appears that the Firth z generally corresponds to a smaller p-value than given in the p.value column, suggesting it is not as well-controlled for inflation.

Does it make sense to enable an option to allow the SE to be back-calculated from the SPA test p-values? This would be similar to the option --firth-se in REGENIE to back-calculate the Firth SE from the LRT p-value.

Thanks
Bryan

**Comment by weizhou0** [comment]
Hi Bryan, 

Thanks a lot for the great suggestion! Now in the version 1.1.6,  we've added this feature, so SE is back-calculated from the SPA test p-values when BETA is estimated using the Firth approx. 

Thanks,
Wei

**Comment by tom-a-bond** [comment]
Hi, what is the name of the flag to back-calculate the SE from the SPA test p-value and firth BETA please?
