### ISSUE TITLE
ERROR! The first variance component parameter estimate is 0

### ISSUE THREAD

**Issue by mkierczak** [saigegit/SAIGE#47]
Hi!

I have 178 individuals, normally distributed phenotype and am getting the following error (with and without co-variates as well as with LOCO on or off):

```
use sparse kinship to fit the model  
cov:  1.309661 -0.01422138 -0.01422138 1.317147  
Variance component estimates:  
[1]   0.0000 236.1409  
Fixed-effect coefficients:  
           [,1]  
[1,] -63.142632  
[2,]   2.013065  
Error in glmmkin.ai_PCG_Rcpp_Quantitative(bedFile, bimFile, famFile, Xorig,  :  
  ERROR! The first variance component parameter estimate is 0  
Calls: fitNULLGLMM -> system.time -> glmmkin.ai_PCG_Rcpp_Quantitative  
Timing stopped at: 20.2 40.78 60.99  
Execution halted
```
 
Any clues as to where the problem can be?

**Comment by weizhou0** [comment]
Hi @mkierczak, 

Have you done inverse normalization for the phenotype? You may use --invNormalize=TRUE in the script. 

Thanks,
Wei

**Comment by mkierczak** [comment]
Yes, I have done both --invNormalize=TRUE and FALSE, followed all previous GitHub issues related to this, included and excluded covariates... Interestingly enough, phenotype is normally distributed. I have tried SAIGE on a couple of datasets and on some it worked well while on other it fails with this error. I am becoming hopeless now...

**Comment by dvg-p4** [comment]
When I was doing some testing last week, I tended to see that error if my sample size was too small (I was using subsets to get step 1 runs to complete faster for debugging). 5000 individuals was about the minimum I needed to consistently avoid that error, so not surprised that you're seeing it with only 178 individuals. Unfortunately getting more individuals is not a straightforward task if you weren't subsetting to begin with.

**Comment by saigegit** [comment]
Thank you very much for the discussion and we are very sorry for our late reply. 
Note that SAIGE and several other programs use asymptotic approaches to make it scalable for big data sizes. To have a more accurate model fitting, the GMMAT R package could be a good one to use. 
[https://cran.r-project.org/web/packages/GMMAT/index.html](https://cran.r-project.org/web/packages/GMMAT/index.html
)

Thanks,
Wei
