### ISSUE TITLE
Use M_PI from math.h instead of PI in src/CCT.cpp

### ISSUE THREAD

**Issue by mverkerk** [saigegit/SAIGE#5]
To prevent the compiler message of not find the 'PI' macro definition in src/CCT.cpp - I have added:

#define _USE_MATH_DEFINES

before: 

#include <math.h>

And replaced all instances of: PI to M_PI (from math.h).

**Comment by weizhou0** [comment]
Hi @mverkerk, 

We have updated this in version 1.0.1. 

Thanks,
Wei
