### ISSUE TITLE
About Pvalue

### ISSUE THREAD

**Issue by SheaCheng2000** [saigegit/SAIGE#50]
Hi, 

Did you use P-value adjustment method (e.g., false discovery rate) when you calculate the P-value of Burden or SKAT in SAIGE-GENE?

Thanks,
Shea

**Comment by weizhou0** [comment]
Hi Shea, 

We don't have any P-value adjustment method when calculate the P-value of Burden or SKAT in SAIGE-GENE. 

Thanks,
Wei

**Comment by SheaCheng2000** [comment]
Got it :) 
Thanks!

**Comment by SheaCheng2000** [comment]
Hi,

May I ask another question about P-value :)
When you calculated P-value, you used one-tailed test, right?  I am not so good at statistics, just extrapolated from your code ` pchisq(...,lower.tail=False)`.  From the R documentation, "lower.tail=False" means[ probability P[X>x]](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/Chisquare)
In my understanding, the essence of p-value calculation in burden test of one certain gene/region should be a 2*2 chi-square test (case vs control and observed vs expected). From the plot and formula of chi-square(df=1), it should be one-tailed. Did I understand it correctly?

Thanks again,
Shea

**Comment by saigegit** [comment]
Hi Shea, 

Yes your understanding is correct expect that in the mode we use, covariates are included, while accounting for sample relatedness and unbalanced case control ratios. 

Thanks,
Wei
