### ISSUE TITLE
Justification for 0.125 GRM sparsity threshold

### ISSUE THREAD

**Issue by tom-a-bond** [saigegit/SAIGE#51]
Hi, I am wondering what the justification for the default GRM sparsity threshold (--relatednessCutoff=0.125) is in createSparseGRM.R please?
In FastGWA, which appears to use a sparse GRM for the same reasons as SAIGE (please correct me if this is wrong!), a sparsity threshold of 0.05 is the default.

**Comment by tom-a-bond** [comment]
Hi, just a polite reminder on this.

**Comment by saigegit** [comment]
Hi @tom-a-bond, 

We are so sorry for our super late reply. In case that it is helpful, we have compared difference relatedness cutoffs in the SAIGE-GENE+ paper (SFigure 1)

[https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-022-01178-w/MediaObjects/41588_2022_1178_MOESM1_ESM.pdf](https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-022-01178-w/MediaObjects/41588_2022_1178_MOESM1_ESM.pdf )

Thanks,
Wei
