### ISSUE TITLE
Optimum plink file for Null and use of Sparse GRM

### ISSUE THREAD

**Issue by Richard-Packer** [saigegit/SAIGE#52]
Firstly really excellent new documentation.

I have a couple of questions which were addressed in the older version of the package but haven't been explicitly addressed here. I was wondering the optimum input for the null model stage. My analysis is in UK Biobank and I have historically used the directly genotyped data, for older versions of SAIGE I filtered that for MAF and Hardy Weinberg, I note that it now has a filter option for MAF. I have also experimented with prunning for LD  in addition to MAF but found that reduced the SNPs to an amount lower than ideal (~100K rather than the preferred 400K given sample sizes of some of the phenotypes). 

Related to this, what is the advantage from generating a Sparse GRM in the context of single variant testing. In my own work I intend to run ~35 GWAS on created phenotypes and creating a single sparse model seems ideal. Does this 'cost' anything in terms of the association anaylsis step, just wondering which is perferable the 'full GRM' or 'sparse'.

**Comment by saigegit** [comment]
Hi @Richard-Packer, 

Very sorry for our late reply. For UKBB analysis, we've found using a Sparse GRM is usually sufficient as the sample relatedness is not that heavy. If you are using the sparse GRM in Step 2, please use version >= 1.1.8, which solves an SPA convergence issue. 

Thanks,
Wei
