### ISSUE TITLE
Documentation site for saige-gene+ step 2 seem broken

### ISSUE THREAD

**Issue by Alexander-Stuckey** [saigegit/SAIGE#53]
Hi,

The documentation site for saige-gene+ step 2 seems to be broken on my end, with images not displaying.
![Screenshot 2022-09-20 at 13 51 56](https://user-images.githubusercontent.com/13140057/191263104-f61eec2a-9ece-475d-af66-1d1fd4680f8a.png)

Cheers,
Alex

**Comment by saigegit** [comment]
Now it's fixed. Thanks!
