### ISSUE TITLE
Installation error "Failed to build package statgen/savvy"

### ISSUE THREAD

**Issue by daniel-hui** [saigegit/SAIGE#54]
Hi Wei, 

We are interested in using SAIGE but I am having trouble installing it. I am working on an HPC cluster running CentOS Linux release 7.8.2003. Once I run `R CMD INSTALL SAIGE`, I get an error:

```
Command failed: ['/opt/software/cmake/3.21.1/bin/cmake', '--build', '/home/dahui/tools/SAIGE/thirdParty/cget/cget/build/tmp-5820afe525fb48749c7d65cb1bf3716f/build', '--config', 'Release', '--', '-j', '80']
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
```

 I tried installing both with and without Conda environment but am having the same issue. The issue seems to be that the package statgen/savvy is not being installed. I saw this old issue (https://github.com/weizhouUMICH/SAIGE/issues/36) which suggested first:

```
cd /SAIGE/
rm -rf thirdParty/cget
cget install -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" --prefix thirdParty/cget -f thirdParty/requirements.txt
```

But this also failed. Finally I went to the statgen/savvy github (https://github.com/statgen/savvy) and tried:

`conda install -c conda-forge -c bioconda savvy`

But this failed as well. Do you know what the issue is? Thanks.

**Comment by saigegit** [comment]
Hi @daniel-hui, 

Have you checked the discussion here 
https://github.com/saigegit/SAIGE/pull/19

@jonathonl may have some idea about this issue to install savvy on Centos. 

Thanks,
Wei

**Comment by jonathonl** [comment]
Can you provide the error message(s) printed prior to the `Command Failed` line when running `R CMD INSTALL SAIGE`?

**Comment by daniel-hui** [comment]
Here's all the output:

`R CMD INSTALL SAIGE`
\* installing to library ‘/home/dahui/R/x86_64-pc-linux-gnu-library/3.6’
\* installing *source* package ‘SAIGE’ ...
\** using staged installation
Ignore package xz
Downloading https://github.com/statgen/savvy/archive/v2.1.0.tar.gz
Extracting archive /project/ritchie07/personal/daniel/tools/SAIGE/thirdParty/cget/cget/build/tmp-38f77840f03d4eedb3f707d3f8d66526/v2.1.0.tar.gz ...
Can't find file cmake
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
\* removing ‘/home/dahui/R/x86_64-pc-linux-gnu-library/3.6/SAIGE’
\* restoring previous ‘/home/dahui/R/x86_64-pc-linux-gnu-library/3.6/SAIGE’

**Comment by saigegit** [comment]
Hi Daniel,

Is it possible to use the conda environment to install SAIGE? We found this
is the easiest way.
https://saigegit.github.io/SAIGE-doc/docs/Installation_conda.html

Thanks,
Wei

**Comment by Sophia20230711** [comment]
Hello,

Recently, I also want to install SAIGE in my server, which is unable to connect to the Internet. I tried the installation  ways , conda, source code, but all of them failed. And by source code, the issue is:

`Unexpected error: <class '0SError'>
[Errno socket error] [Errno -2] Name or service not known
Failed to build package statgen/savvy`

Do you know how to deal with this problem? Thanks!
