### ISSUE TITLE
Can --invNormalize be turned off for any value of variance?

### ISSUE THREAD

**Issue by mariosaare** [saigegit/SAIGE#55]
Dear developer,

I am trying to compare SAIGE output to REGENIE output. I am using a continuous variable with values close to zero (range -0.03 - 0.66). REGENIE runs without the option --apply-rint (apply rank inverse normal transformation), but I cannot run SAIGE without normalization. I get the following error message:

`Error in glmmkin.ai_PCG_Rcpp_Quantitative(bedFile, bimFile, famFile, Xorig,  :
  WARNING: variance of the phenotype is much smaller than 1. Please consider invNormalize=T
Calls: fitNULLGLMM -> system.time -> glmmkin.ai_PCG_Rcpp_Quantitative
`

Is there any way to avoid normalization in SAIGE? If not, are the normalization methods equivalent, so that I could compare the outputs after normalization in REGENIE as well?

Best regards,
Mario Saare

**Comment by saigegit** [comment]
Hi @mariosaare, 

Very sorry for our late reply. SAIGE tries to fit a linear mixed model. When the variance of the phenotype is too small or too large, the algorithm can't converge well, so the inverse normalization is required. 

Thanks,
Wei
