### ISSUE TITLE
llapack linking error (refers to issue 118 in old repository)

### ISSUE THREAD

**Issue by mverkerk** [saigegit/SAIGE#6]
Not sure where ${LAPACK_LIBS} should be defined ( looking at src/Makevars ), but adding

" -L../lib64 -llapack " to:

PKG_LIBS = $(ZLIB_LIB) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) -L../thirdParty/cget/lib/ -L../thirdParty/cget/lib64/ -lsuperlu -lzstd -L ../lib64 -llapack

Makes the compile work out on Centos 8 out of the box.

**Comment by weizhou0** [comment]
Hi @mverkerk, 
We have add it to the updated version 1.0.1. 

Thanks,
Wei
