### ISSUE TITLE
Default for `--maxMAF_in_groupTest` is not what the help message says it is

### ISSUE THREAD

**Issue by dvg-p4** [saigegit/SAIGE#61]
Help message for `step2_SPAtests.R` claims the default for `--maxMAF_in_groupTest` is `0.01` as when running from R; actual default seems to be `0.0001,0.001,0.01`

**Comment by weizhou0** [comment]
Hi @dvg-p4,

Thanks for reporting the issue! I've fixed it in version 1.1.6.3

Thanks,
Wei
