### ISSUE TITLE
--isCovariateOffset option and functionality

### ISSUE THREAD

**Issue by kousathanas** [saigegit/SAIGE#64]
Hi @weizhouUMICH , 

Could you explain what --isCovariateOffset does in the new SAIGE version? 
This is set to TRUE by default but I experienced cases where setting this to TRUE can lead to non-convergence of the null fit and also not appropriate covariate adjustment.

More specifically, this happened for phenotypes for which the sex covariate had a strong effect. Failure to adjust for the sex covariate led to inflation of genetic effects.

Setting this option to FALSE, fixed the issue. Also, the previous SAIGE v0.44.6.5 did not produce this issue (presumably does not perform the offset adjustment and estimates the covariates).

**Comment by weizhou0** [comment]
Hi @kousathanas, 

When --isCovariateOffset =TRUE, we first fit a null model without random effects (no sample relatedness is accounted for), in which the coefficients of covariates are estimated. Then the estimated effects of all covariates are included in the null random effect model as an offset, meaning the coefficients of covariates are not updated iteratively when random effects are estimated. The approach has been used in several biobank-scale GWAS methods to achieve a further reduce in computation time, especially when there are many covariates are included, although the model fitting ignores the covariance between covariates (fixed effects) and random effects. Our empirical evaluation in the UKBB data showed the association test results for binary phenotypes tend to be robust to this option. But you are right, for some phenotypes, this option can lead to inaccurate association results and you will need to set --isCovariateOffset=FALSE. 

Thanks,
Wei
