### ISSUE TITLE
Imputation of missing genotypes

### ISSUE THREAD

**Issue by daniel-hui** [saigegit/SAIGE#65]
Hi Wei,

I was looking through the SAIGE documentation (https://saigegit.github.io/SAIGE-doc/docs/single_step2.html) and saw that missing genotypes are imputed:

> By default, missing genotypes/dosages will be imputed as the best guessed gentoypes/dosages (as round(2*freq) with –impute_method=best_guess). Note that currently dropping samples with missing genotypes/dosages is not supported

I'm curious if there is any recommendation on how to deal with cohorts with high genotype missingness? For instance, we have a dataset where a portion of individuals were whole-genome sequenced, and another portion that were genotyped on array. So when we combine them many variants will have high missingness, despite all variants passing quality-control. If they are just imputed using "round(2*freq)" this is not preferred, but we would like to analyze them all together. Thanks.

Daniel

**Comment by weizhou0** [comment]
Hi Daniel, 

I think a better way to analyze the cohorts together is to first impute the individuals who were genotyped on array from some reference panels, such as HRC and TOPMed. 

Thanks,
Wei
