### ISSUE TITLE
Download failed with error 503 for: //github.com/statgen/savvy/archive/v2.1.0.tar.gz

### ISSUE THREAD

**Issue by 7JVST** [saigegit/SAIGE#68]
I am trying to install SAIGE from source codes using the commands shown in https://saigegit.github.io/SAIGE-doc/docs/Installation_sourcecode.html but still persistently getting this error. Please let me know how to fix this error.

` installing to library ‘/home/Justin/R/x86_64-pc-linux-gnu-library/4.2’

installing source package ‘SAIGE’ ...
** using staged installation
Ignore package xz
Downloading https://github.com/statgen/savvy/archive/v2.1.0.tar.gz
[----------------------------------------------------------------------] 0%
Download failed with error 503 for: //github.com/statgen/savvy/archive/v2.1.0.tar.gz
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
removing ‘/home/Justin/R/x86_64-pc-linux-gnu-library/4.2/SAIGE’`

**Comment by weizhou0** [comment]
Hi @7JVST, 

It looks like there was a connection problem to download the savvy library. Now the URL link https://github.com/statgen/savvy/archive/v2.1.0.tar.gz works. Can you please try again?

Thanks,
Wei
