### ISSUE TITLE
double free or corruption & memory not mapped

### ISSUE THREAD

**Issue by changxuling** [saigegit/SAIGE#69]
Hi,

I am recently running some analysis with SAIGE but encountered the following two issues (some of the chromosomes can run through while some cannot and the error shown up). Could you please suggest how to fix these?

Thanks!

[log_memory not mapped.txt](https://github.com/saigegit/SAIGE/files/10319804/log_memory.not.mapped.txt)
[log_double free or corruption.txt](https://github.com/saigegit/SAIGE/files/10319805/log_double.free.or.corruption.txt)

**Comment by weizhou0** [comment]
Hi @changxuling, 

Can you please show the log messages output by the program before the error occurred?  

Thanks,
Wei

**Comment by changxuling** [comment]
> Hi @changxuling,
> 
> Can you please show the log messages output by the program before the error occurred?
> 
> Thanks, Wei

![1](https://user-images.githubusercontent.com/10111213/214477371-61c6450b-1e3e-4f6f-9d5d-4e35f0f8289b.jpg)
Hi Wei,

Log message output attached. And this "memory not mapped" error seems can be addressed by changing the temp folder to a larger folder. However, after solve this, it changed to "double free or corruption (!prev)".

![2](https://user-images.githubusercontent.com/10111213/214477513-69fe4076-8d5e-454e-b6da-2414e77402cf.jpg)


(2023-01-24 00:18:25) ---- Analyzing Chunk 5 :  chrom InitialChunk ---- 
Completed 10000/10000 markers in the chunk.
6546 markers were tested.
Firth approx was applied to 217 markers. 217 sucessfully converged.
write to output
   user  system elapsed 
259.907   7.299 253.937 
isVcfEnd  FALSE 
(2023-01-24 00:19:10) ---- Analyzing Chunk 6 :  chrom InitialChunk ---- 
*** Error in `/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/R': double free or corruption (!prev): 0x0000559aad1b19b0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81359)[0x7f3f30ade359]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so(_ZN12ComputeExactD1Ev+0x1c)[0x7f3f2afe499c]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so(_Z10SKAT_ExactPiiS_PdS0_iiiS_S0_S0_S0_S_S0_S0_S0_id+0x14c)[0x7f3f2afe5d1c]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so(_Z17SKATExactBin_WorkRN4arma3MatIdEERNS_3ColIdEES5_jRNS3_IyEES7_S2_iidi+0xefd)[0x7f3f2aff185d]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so(_ZN5SAIGE10SAIGEClass13getMarkerPvalERN4arma3ColIdEERNS2_IyEES6_RdS7_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESE_dS7_S7_S7_RbS4_SF_bS4_bS7_S7_SE_SE_S7_S7_RNS1_3RowIdEESF_SF_b+0x1285)[0x7f3f2afa5d75]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so(+0x58e04)[0x7f3f2aec3e04]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/library/SAIGE/libs/SAIGE.so(_SAIGE_mainMarkerInCPP+0x273)[0x7f3f2af08293]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0xff652)[0x7f3f30f2a652]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0xffc36)[0x7f3f30f2ac36]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x13dda1)[0x7f3f30f68da1]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x80)[0x7f3f30f83560]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x15a2bf)[0x7f3f30f852bf]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19e)[0x7f3f30f8608e]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x147d41)[0x7f3f30f72d41]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x80)[0x7f3f30f83560]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x15a2bf)[0x7f3f30f852bf]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19e)[0x7f3f30f8608e]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x147d41)[0x7f3f30f72d41]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x80)[0x7f3f30f83560]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x15a2bf)[0x7f3f30f852bf]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_applyClosure+0x19e)[0x7f3f30f8608e]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x2b1)[0x7f3f30f83791]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x15b869)[0x7f3f30f86869]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x5b9)[0x7f3f30f83a99]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x5b9)[0x7f3f30f83a99]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x15b869)[0x7f3f30f86869]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x5b9)[0x7f3f30f83a99]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_eval+0x5b9)[0x7f3f30f83a99]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(Rf_ReplIteration+0x256)[0x7f3f30fb8336]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(+0x18d6f9)[0x7f3f30fb86f9]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/../../lib/libR.so(run_Rmainloop+0x49)[0x7f3f30fb87a9]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/R(main+0x1d)[0x559aa26b805d]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3f30a7f585]
/home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/R(+0x108d)[0x559aa26b808d]
======= Memory map: ========
559aa26b7000-559aa26b8000 r--p 00000000 103:01 6031966                   /home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/R
559aa26b8000-559aa26b9000 r-xp 00001000 103:01 6031966                   /home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/R
559aa26b9000-559aa26ba000 r--p 00002000 103:01 6031966                   /home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/R
559aa26ba000-559aa26bb000 r--p 00002000 103:01 6031966                   /home/ec2-user/miniconda3/envs/RSAIGE/lib/R/bin/exec/R


Thanks.

With regards
Shirley

**Comment by pettyalex** [comment]
This is coming from the same place as https://github.com/saigegit/SAIGE/issues/83
