### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by LaporteF** [saigegit/SAIGE#7]
Hi,

I tried to install SAIGE using conda. The python version used in your environment is the 2.7 which do not run with classical workflow manager as snakemake. I updated this using python version 3.10.
But I runned into an other error. When I launched this code line:

R CMD INSTALL --library=path_to_final_SAIGE_library SAIGE

I had the following error:

Downloading https://github.com/statgen/savvy/archive/v2.0.1.tar.gz                                                                                                                                                                             [----------------------------------------------------------------------]    0%                                                                                                                                                             Download failed with error 502 for: //github.com/statgen/savvy/archive/v2.0.1.tar.gz 

Is there any bypass concerning this error?

Regards

**Comment by saigegit** [comment]
Hi,
It seem the error is because of the internet connection issue. Can you try again? 
Thanks,
Wei

**Comment by LaporteF** [comment]
Apparently, a wget of the link works but again the downloading within the R package installation SAIGE does not work.

I tried to suppress the configuration file within the SAIGE folder and install savvy and superlu using conda.
I achieved to install the R package SAIGE but the function step1_fitNULLGLMM.R is unknown when I tried to launch "step1_fitNULLGLMM.R --help".
I used the previous version using a conda environment and an installation through bioconda. I believe it is not the same way to launch the algorithm using this method. Am I constrain to launch R and then SAIGE within the R terminal ?

Is the new version will be available on bioconda soon?

Regards.

**Comment by LaporteF** [comment]
It works when I launch an Rscript using the files "step1_fitNULLGLMM.R" and "step2_SPAtest.R" within ./SAIGE/extdata/
I will work with that until the update of the bioconda version.

SAIGE is still simple to use once the installation made. Thanks you for the last update, I had some issues with the previous one about memory size. I hope this one will handle the size of our dataset.

Regards.
