### ISSUE TITLE
SAIGE installation error

### ISSUE THREAD

**Issue by kousikbioinfo** [saigegit/SAIGE#74]
I am trying to install SAIGE through conda by following [this](https://saigegit.github.io//SAIGE-doc/docs/Installation_conda.html), but getting error R CMD INSTALL.

```
(RSAIGE) [Kousik@AZ-scp - Software] $ R CMD INSTALL SAIGE
* installing to library ‘/projects/cgr/users/klds407/.conda_env/RSAIGE/lib/R/library’
* installing *source* package ‘SAIGE’ ...
** using staged installation
Ignore package xz
Downloading https://github.com/statgen/savvy/archive/v2.1.0.tar.gz
Download failed with error 501 for: //github.com/statgen/savvy/archive/v2.1.0.tar.gz
Failed to build package statgen/savvy
ERROR: configuration failed for package ‘SAIGE’
* removing ‘/projects/cgr/users/klds407/.conda_env/RSAIGE/lib/R/library/SAIGE’
(RSAIGE) [Kousik@AZ-scp - Software] $ cd /projects/cgr/users/klds407/.conda_env/RSAIGE
```

I'm not sure how to fix it from here. Could anybody help?

**Comment by weizhou0** [comment]
Hi @kousikbioinfo, 

It looks like there was a connection problem to download the savvy library. Now the URL link https://github.com/statgen/savvy/archive/v2.1.0.tar.gz works. Can you please try again? 

Thanks,
Wei
