### ISSUE TITLE
Back calculated SE

### ISSUE THREAD

**Issue by tom-a-bond** [saigegit/SAIGE#77]
Hi,

We would like to use the SE back-calculated from the SPA test p-values and BETA estimated using the Firth approx, as detailed here: https://github.com/saigegit/SAIGE/issues/46

Would you mind clarifying how this is obtained please- i.e. is the SE column automatically calculated in this way when firth regression is turned on, or does the back-calculation have to be requested explicitly?

Many thanks in advance,
Tom

**Comment by weizhou0** [comment]
Hi Tom, 

I'm so sorry for my late reply! The SE column automatically calculated in this way when firth regression is turned on. 

Thanks,
Wei

**Comment by tom-a-bond** [comment]
Brilliant, many thanks for confirming this!
