### ISSUE TITLE
No parameter for "IsDropMissingDosages", how to handle values not present in VCF?

### ISSUE THREAD

**Issue by Ankeet3** [saigegit/SAIGE#79]
I am trying to run step2_SPATests.R, I am running into this error "at least one subject requested is not in the VCF file". I am assuming that this error arises from a mismatch in samples between the model and the VCF file. Earlier, we had the option to drop missing dosages via the "IsDropMissingDosages" parameter, but that doesn't seem to be there in the latest version. How do I deal with this situation? Any help will be really appreciated.

**Comment by saigegit** [comment]
Hi @Ankeet3, 

You may use --subSampleFile to specify the sample IDs that are included in Step 1 and will be also included in Step 2 

Thanks,
Wei
