### ISSUE TITLE
Overlap of samples in inputGenoFile and Model File for Step2 GBAT

### ISSUE THREAD

**Issue by Ankeet3** [saigegit/SAIGE#86]
I am confused about the amount of overlap allowed between samples in the input file and samples in the model file for step2 GBAT. Are we not allowed to run input files which do not contain all samples present in the model file? Is there a way to run the input files just for samples that are common between the input sample file and the model file?

**Comment by weizhou0** [comment]
Hi @Ankeet3, 

You may use --subSampleFile to specify IDs of samples that are included in Step 1 and will be also included in Step 2. 
Here is the help message
"Path to the file that contains one column for IDs of samples that are included in Step 1 and will be also included in Step 2. This option is used when any sample included in Step 1 but does not have dosages/genotypes for Step 2. Please make sure it contains one column of sample IDs that will be used for subsetting samples from the Step 1 results for Step 2 jobs. Note: This option has not been fully evaluated. If more than 5% of the samples in Step 1 are missing in Step 2, please consider re-run Step 1."

Thanks,
Wei
