### ISSUE TITLE
nThreads support for SAIGE step2

### ISSUE THREAD

**Issue by ofrei** [saigegit/SAIGE#9]
Hi,

I've been using previous version of SAIGE (v0.44.6.5), and it didn't allow ``--nThreads`` in the second step, giving the following error:
```
--nThreads is invalid for the second step. It only works for the first step in Saige analysis.
```

Is this limitation addressed in v1.0.1 ? 

Ideally in step2 I'd like to submit one SAIGE job per chromosome, and use multiple threads per chromosome. This makes overall workflow easier, and consistent with how one usually runs GWAS in regenie and plink2.

**Comment by weizhou0** [comment]
Hi @ofrei, 

SAIGE does not support multiple threads in Step 2. Practically, --idstoIncludeFile or --rangestoIncludeFile can be used to split the jobs for each chromosome. For example, when we used google cloud to run UKBB jobs, for each chromosome using a VM with 32 CPUs, 32 jobs were run simultaneously, each with a marker list specified using --idstoIncludeFile (alternatively ranges with chr, start, end can be specified using --rangestoIncludeFile)

Thanks,
Wei

**Comment by ofrei** [comment]
@weizhou0 thanks! That's good to know. I'll use --idstoIncludeFile or --rangestoIncludeFile options
