### ISSUE TITLE
ERROR: 2 has Phased = 2 (not 0)

### ISSUE THREAD

**Issue by raminsalmas** [saigegit/SAIGE#91]
I'm running step 2 but facing the error: "ERROR: 2 has Phased = 2 (not 0)"

I'm wondering if anyone could advise me on how to solve it?

Best,

**Comment by saigegit** [comment]
Hi @raminsalmas, 

The error is because the version of your bgen file is not 1.2 with 8 bits
If you used PLINK to make the bgen files, adding 
`--export bgen-1.2 bits=8`
can solve the problem. 

Thanks,
Wei
