### ISSUE TITLE
Saige Docker in google cloud registry

### ISSUE THREAD

**Issue by akhilpampana** [saigegit/SAIGE#93]
Hello, 

I am trying to check if there is a Docker image available for SAIGE in the Google Cloud Registry to run a GWAS analysis in the All Of Us platform. Is the Docker image currently available in GCP, or are there plans to include it in the GCP registry? I would greatly appreciate any information on this matter as it is currently impeding my GWAS efforts. Please let me know if there are any updates regarding this.

Regards
Akhil

**Comment by akhilpampana** [comment]
Thank you so much for the information and clarification.

**Comment by pettyalex** [comment]
When I did this last year, All of Us did not yet support the "Artifact Registry", meaning that we had to use Container Registry instead. I had to create a new Google Cloud project because once you've upgraded to Artifact Registry, you cannot go back to the older container registry.

**Comment by akhilpampana** [comment]
Oh that explains, I believe they have artifact registry thing set now as they enabled Cromwell and wdl to run pipelines which I assume should be done through the google cloud registry.

**Comment by pettyalex** [comment]
There are two completely different, incompatible registries that can be used to store container images in google cloud, Container Registry and Artifact Registry: https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry

Last I was in there, only Container Registry worked for All of Us

**Comment by akhilpampana** [comment]
OK, I will give it a try and see if the artifact registry works or not, I will keep you posted
