### ISSUE TITLE
Minor allele count in SAIGE vs SAIGE-GENE

### ISSUE THREAD

**Issue by daniel-hui** [saigegit/SAIGE#98]
Thank you for developing both of these tools. So, for SAIGE the default minimum minor allele count (MAC) is 20, and as I understand it's not lower as test statistics can become inflated with low minor allele count. For SAIGE-GENE, there is no MAC threshold, as it seems to estimate some model parameters separately for bins of variants with MAC<20. But, say there is a gene that only has one loss-of-function variant, say with a MAC of 15 -- then this would be included in the SAIGE-GENE results, but would be filtered out from running SAIGE normally? Would it make sense in some analyses to increase the MAC threshold to 20 for SAIGE-GENE as well? Thanks.

**Comment by weizhou0** [comment]
Hi @daniel-hui, 
As you mentioned, the main difference between single-variant association tests (SAIGE) and set-based tests (SAIGE-GENE) is that in set-based tests, we test rarer variants. Single-variant assoc tests are underpowered for those very rare variants, e.g. MAC < 20,  so we don't test those very rare variants in SAIGE. 
But we can still test them if needed. I've added an example in the documentation. 
[https://saigegit.github.io/SAIGE-doc/docs/single_example.html#example-5-include-rarer-variants-in-the-single-variant-assoc-tests-minmac05](https://saigegit.github.io/SAIGE-doc/docs/single_example.html#example-5-include-rarer-variants-in-the-single-variant-assoc-tests-minmac05
)

Please feel free to re-open the issue if any questions arise. 

Thanks!
Wei
